window.SCHOOLS=[
['Caltech','CA','REA 11/1 · RD 1/4','Required','이론·양자·입자·천체, 매우 높은 연구집중도','Philosophy/HPS option·minor, 과학철학 연결 강함','2026-27 상세 반영','verified'],
['MIT','MA','EA 11/1 · RA 1/4','Required','Course 8 Focused/Flexible, 학부 연구 UROP 강점','Philosophy major/minor; Flexible Physics와 병행 유연','2026-27 상세 반영','verified'],
['Harvard University','MA','REA 11/1 · RD 1/1','Required','Physics concentration, 이론·실험·천체 폭넓음','Philosophy concentration/secondary field 병행 가능','2026-27 상세 반영','verified'],
['Yale University','CT','SCEA 11/1 · RD 1/2','Required','Physics BS/Intensive 및 학부 연구','Physics & Philosophy BA/BS 자체 전공','2026-27 상세 반영','verified'],
['Princeton University','NJ','SCEA 11/1 · RD 1/1','Fall 2027 test-optional','강한 이론·입자·중력·플라즈마 및 독립연구','Philosophy certificate/교과와 과학철학 연결','비용 공식표 확인','verified'],
['Stanford University','CA','REA 11/1 · RD 1/5','Required','SLAC 연계, 입자·천체·응집·AMO·이론','Philosophy major/minor; philosophy of science 강점','비용 공식표 확인','verified'],
['University of Chicago','IL','ED I/EA 11/2 · ED II/RD 1/4','Test-optional 정책 공식페이지 최종 확인','강한 이론물리·우주론·입자, Fermilab/Argonne 접근','Philosophy major/minor와 과학철학 연결 우수','2026-27 비용 확인 중','verified'],
['Harvey Mudd College','CA','ED I/ED II/RD','학교 공식정책 확인','소규모 STEM, 학부 중심 Physics와 Clinic/연구','HMC humanities + Claremont 철학 교과 활용','2026-27 확인 중','review'],
['University of Pennsylvania','PA','ED 11/1 · RD 1/5','SAT/ACT Required','Physics & Astronomy, interdisciplinary 연구','Philosophy major/minor; Penn의 폭넓은 복수전공 구조','2026-27 비용 확인 중','verified'],
['Rice University','TX','ED I/ED II/RD','학교 공식정책 확인','소규모 연구대학, quantum/space/nano 연구','Philosophy major와 병행 가능한 유연한 학부구조','2026-27 확인 중','review'],
['Cornell University','NY','ED/RD','학교 공식정책 확인','LASP, synchrotron, condensed matter 등 연구폭 큼','Philosophy major/minor와 Arts & Sciences 내 병행','2026-27 확인 중','review'],
['Columbia University','NY','ED/RD','학교 공식정책 확인','뉴욕 연구환경, 입자·핵·응집·천체','Philosophy major/concentration, Core와 결합','2026-27 확인 중','review'],
['UCLA','CA','UC 10/1–11/30','UC test-free','대형 연구대학, 입자·플라즈마·천체·응집','Philosophy major/minor 선택 가능','UC 비용 확인 중','verified'],
['UT Austin','TX','EA/RD 일정 공식 확인','학교 공식정책 확인','강한 Physics, McDonald Observatory·quantum·condensed matter','Philosophy major와 병행 가능','2026-27 확인 중','review'],
['Carnegie Mellon University','PA','ED/RD','학교 공식정책 확인','Physics + computation/materials/biophysics 연결','Philosophy의 logic/science 연계가 특히 강점','2026-27 확인 중','review'],
['Brown University','RI','ED 11/1 · RD 1/5','SAT/ACT Required · superscore','Open Curriculum로 Physics 경로 설계 자유도 높음','Philosophy와 double concentration 설계에 유리','FAFSA/CSS: ED 11/2 · RD 2/1; 비용 확인 중','verified'],
['UC Berkeley','CA','UC 10/1–11/30','UC test-free','세계적 Physics 연구, LBNL 연계','Philosophy major와 science/philosophy 교차 탐색','UC 비용 확인 중','verified'],
['Dartmouth College','NH','ED/RD','학교 공식정책 확인','소규모 학부교육 + 연구 접근성','Philosophy major/minor와 병행 용이','2026-27 확인 중','review'],
['University of Michigan–Ann Arbor','MI','EA/RD','학교 공식정책 확인','대형 Physics 연구, 입자·AMO·천체·응집','Philosophy major/minor와 LSA 내 병행','2026-27 확인 중','review'],
['Georgia Tech','GA','EA/RD','학교 공식정책 확인','Physics + engineering/quantum/materials 연결 강함','Philosophy는 School of History & Sociology/Humanities 교과 확인','2026-27 확인 중','review'],
['Pomona College','CA','ED I/II/RD','학교 공식정책 확인','소규모 Physics, Claremont 자원 공유','Philosophy 전공 + 5C 교과, 복수전공 친화','2026-27 확인 중','review'],
['Johns Hopkins University','MD','ED I/II/RD','학교 공식정책 확인','Physics & Astronomy, Space Telescope Science Institute 인접','Philosophy major/minor 병행 가능','2026-27 확인 중','review'],
['Duke University','NC','ED/RD','학교 공식정책 확인','quantum, particle, cosmology, condensed matter','Philosophy major/minor 및 interdisciplinary 조합','2026-27 확인 중','review'],
['University of Notre Dame','IN','REA/RD','학교 공식정책 확인','Physics 연구 + 학부 커뮤니티','Philosophy가 매우 큰 학과, Physics와 병행 매력','2026-27 확인 중','review'],
['Washington University in St. Louis','MO','ED I/II/RD','학교 공식정책 확인','Physics + quantum/materials/biophysics','Philosophy-Neuroscience-Psychology 등 철학 연계 폭넓음','2026-27 확인 중','review'],
['UIUC','IL','EA/RD','학교 공식정책 확인','condensed matter/quantum/AMO 등 최상위권 연구','Philosophy major/minor와 LAS 내 병행','2026-27 확인 중','review'],
['University of Virginia','VA','EA/ED/RD','학교 공식정책 확인','Physics 연구와 학부 thesis 기회','Philosophy major와 College 내 복수전공','2026-27 확인 중','review'],
['New Mexico Tech','NM','Rolling/priority 일정 확인','학교 공식정책 확인','소규모 STEM, astrophysics/geophysics/experimental 강점','철학 전공 규모/병행 옵션 공식 확인 필요','2026-27 확인 중','review'],
['Amherst College','MA','ED/RD','학교 공식정책 확인','소규모 학부 Physics + Five College 자원','Open Curriculum, Philosophy double major에 매우 유연','2026-27 확인 중','review'],
['UC Santa Barbara','CA','UC 10/1–11/30','UC test-free','Kavli, condensed matter, quantum, theory 강점','Philosophy major와 병행 가능','UC 비용 확인 중','verified'],
['University of Washington','WA','RD 중심 일정 확인','학교 공식정책 확인','대형 연구대학, nuclear/particle/AMO/astro','Philosophy major와 병행 가능','2026-27 확인 중','review'],
['University of Florida','FL','EA/RD 일정 확인','학교 공식정책 확인','Physics + astronomy, condensed matter, nuclear','Philosophy major/minor 병행 가능','2026-27 확인 중','review'],
['Vanderbilt University','TN','ED I/II/RD','학교 공식정책 확인','소규모 연구대학 Physics, interdisciplinary 접근','Philosophy major/minor와 복수전공','2026-27 확인 중','review'],
['Bowdoin College','ME','ED I/II/RD','학교 공식정책 확인','학부 중심 Physics, 작은 클래스','Philosophy와 double major에 적합한 liberal arts 구조','2026-27 확인 중','review'],
['Northwestern University','IL','ED 11/1 · RD 1/4','Test-optional','Physics & Astronomy + materials/quantum 연구','Philosophy major/minor와 Weinberg 내 병행','Aid: ED 12/1 · RD 2/1; decisions Dec/Mar','verified'],
['University of Rochester','NY','ED I/II/RD','학교 공식정책 확인','optics/quantum/laser/astro 강점','Philosophy major/minor, Rochester Curriculum 유연','2026-27 확인 중','review'],
['U.S. Naval Academy','MD','별도 nomination/application','별도 요건','Physics 전공 + 군사/공학 교육','Philosophy 관련 humanities 교과; 복수전공 구조 제한 확인','연방 사관학교 비용구조','review'],
['New York University','NY','ED I/II/RD','학교 공식정책 확인','Physics + Center for Cosmology/Particle Physics','Philosophy가 세계적으로 강함; 조합 매력 큼','2026-27 확인 중','review'],
['Michigan State University','MI','EA/Rolling','학교 공식정책 확인','FRIB 핵물리 강점, 대형 연구환경','Philosophy major/minor 병행 가능','2026-27 확인 중','review'],
['Haverford College','PA','ED I/II/RD','학교 공식정책 확인','학부 중심 Physics + Tri-Co 자원','Philosophy와 double major/교차수강 유리','2026-27 확인 중','review'],
['University of Wisconsin–Madison','WI','EA/RD','학교 공식정책 확인','강한 Physics, IceCube/particle/AMO/condensed matter','Philosophy major와 L&S 내 병행','2026-27 확인 중','review'],
['Wesleyan University','CT','ED I/II/RD','학교 공식정책 확인','소규모 Physics, 학부 연구 중심','Philosophy와 자유로운 double major','2026-27 확인 중','review'],
['UC San Diego','CA','UC 10/1–11/30','UC test-free','Physics + astrophysics/condensed matter/biophysics','Philosophy major/minor, science studies 연결 가능','UC 비용 확인 중','verified'],
['Swarthmore College','PA','ED I/II/RD','학교 공식정책 확인','소규모 Physics + Honors, Tri-Co 접근','Philosophy와 double major에 좋은 liberal arts 환경','2026-27 확인 중','review'],
['Georgetown University','DC','EA/RD','학교 공식정책 확인','학부 Physics, DC 연구자원','Philosophy core/major가 강해 철학 병행에 유리','2026-27 확인 중','review'],
['Williams College','MA','ED/RD','학교 공식정책 확인','소규모 최상급 학부 Physics, 연구 밀접','Philosophy double major에 적합','2026-27 확인 중','review'],
['Washington and Lee University','VA','ED I/II/RD','학교 공식정책 확인','소규모 Physics, 학부 교수 접근성','Philosophy major와 복수전공 친화','2026-27 확인 중','review'],
['Emory University','GA','ED I/II/RD','학교 공식정책 확인','Physics + biophysics/materials, interdisciplinary','Philosophy major와 병행 가능','2026-27 확인 중','review'],
['Boston University','MA','ED I/II/RD','학교 공식정책 확인','Physics + photonics/particle/condensed matter','Philosophy major/minor와 병행','2026-27 확인 중','review'],
['William & Mary','VA','ED I/II/RD','학교 공식정책 확인','학부 중심 Physics + Jefferson Lab 접근','Philosophy major와 liberal arts 조합','2026-27 확인 중','review']
];